### ISSUE TITLE
how to estimate tau?

### ISSUE THREAD

**Issue by james20141606** [luphord/nelson_siegel_svensson#1]
Hi! I have read your documentation and some source code. It seems it can estimate betas given tau, but how can I get tau from the data?

**Comment by luphord** [comment]
You can use the `calibrate_ns_ols` and `calibrate_nss_ols` functions in the `calibrate` module (see also [Usage](https://nelson-siegel-svensson.readthedocs.io/en/latest/usage.html) and [Module docs](https://nelson-siegel-svensson.readthedocs.io/en/latest/nelson_siegel_svensson.html#module-nelson_siegel_svensson.calibrate)):

        import numpy as np
        from nelson_siegel_svensson.calibrate import calibrate_ns_ols

        t = np.array([0.0, 0.5, 1.0, 2.0, 3.0, 4.0, 5.0, 10.0, 15.0, 20.0, 25.0, 30.0])
        y = np.array([0.01, 0.011, 0.013, 0.016, 0.019, 0.021, 0.026, 0.03, 0.035, 0.037, 0.038, 0.04])

        curve, status = calibrate_ns_ols(t, y, tau0=1.0)  # starting value of 1.0 for the optimization of tau
        assert status.success
        print(curve)

These methods will optimize `tau` (or `tau1` and `tau2`) using nonlinear optimization while chosing optimal `betas` using ordinary least squares (OLS). This is a rather primitive approach, but it is the only one currently implemented. Are you interested in any other specific calibration method?
