### ISSUE TITLE
Cannot iterate over results of calibrate_nss_ols process to collect parameters

### ISSUE THREAD

**Issue by 06agyepo** [luphord/nelson_siegel_svensson#16]
* Nelson-Siegel-Svensson Model version:
* Python version: 3.8.5
* Operating System: windows

### Description
My question or issue is with the calibrate_nss_ols or calibrate_ns_ols method. It would be great to be able to iterate through the results of the calibration.

As it stands, I cannot select the parameters of the calibrated nelson siegel or nelson siegel svensson model for later use. It appears the only way to use the parameters or results of the calibrated model is to manually copy them and paste them as follows:

NelsonSiegelCurve(beta0=0.04201739383636799, beta1=-0.031829031569430594, beta2=-0.
˓→026797319779108236, tau=1.7170972656534174)

This manual process appears inefficient to me. It would be great to have the results of the calibration in list format [] so that we can index or iterate through the results of the calibrate_nss_ols  method to obtain and cycle through the parameters like so: beta0 = results[0], beta1 = results[1], ... ,tau2 = results[5]

### What I Did
curve, status = calibrate_nss_ols(t, y) 

curve variable above only returns an object that doesn't allow me to index or select and assign the parameters of the calibrated model to a variable. It would be fantastic if the results of the calibration was in a list format so that we can index through the parameters, select them and assign them to a variable for reuse...
  
Thank you so much for taking the time to read this and thank you for your work on this api!! Overall it's a great product and the world owes you a debt of gratitude for this work.

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by luphord** [comment]
I am not sure if I understand you correctly, but all calibrated parameters are simply members of the curve object. So you can do e.g. `curve.beta0` to access the calibrated beta0 parameter. Also, the curve is a dataclass, so you can do `dataclasses.asdict(curve)` to transform it into a parameter dictionary.

**Comment by 06agyepo** [comment]
Wow thanks so much for this!! I was clearly lacking in knowledge on this topic… this is great, it answers my question elegantly! 😊


[Addenda Capital Logo]<https://addendacapital.com/>
Kwaku Apraku, MFin, CFA
Senior Analyst and Money Market Trader
***@***.******@***.***>
T. 226-780-2316

130 Macdonell Street, Priory Square, Guelph (Ontario)  N1H 6P8
addendacapital.com<https://addendacapital.com>

**Comment by luphord** [comment]
Great! Then I will close this issue as resolved.
