### ISSUE TITLE
is it possible to estimate different yield curves on the same chart?

### ISSUE THREAD

**Issue by rafaelgrilli** [luphord/nelson_siegel_svensson#3]
Dear colleagues, I was wondering if it is possible to plot more than one estimated yield curve on the same chart. 
For instance, NS and NSS for the same country, both for a set of extra countries, for comparative purposes. 
Thank you,
Rafael

**Comment by luphord** [comment]
I do not see any reason why this should not be possible. E.g. `matplotlib` will automatically execute multiple plot commands within a common chart.

Closing this issue as it is not related to `nelson_siegel_svensson`.
