### ISSUE TITLE
getting curve from slope, curvature

### ISSUE THREAD

**Issue by lorrp1** [luphord/nelson_siegel_svensson#4]
Hello, 
i have slope, curvature and i would like to get the nelson_siegel curve (the b0, b1, b2 parameters)

**Comment by luphord** [comment]
Could you be more specific what your issue is with this library?

**Comment by lorrp1** [comment]
@luphord I just don’t understand how to get this for example : NelsonSiegelCurve(beta0=0.04201739383636799, beta1=-0.031829031569430594, beta2=-0.026797319779108236) from level, slope and curvature values

**Comment by luphord** [comment]
@lorrp1 Are you still interested in this topic or can the issue be closed?
