### ISSUE TITLE
Calibrating NS parameters for multiple term structures together

### ISSUE THREAD

**Issue by BenJordan23** [luphord/nelson_siegel_svensson#5]
* Nelson-Siegel-Svensson Model version: 0.4.2
* Python version: 3.7.8
* Operating System: Mac OS 11.2.3

### Description

I was wondering if it is possible to calibrate the decay parameter lambda for multiple term structures like in this paper:
![image](https://user-images.githubusercontent.com/28095507/111164266-34acd100-859e-11eb-8260-77675d43258f.png)

I have term structure data for multiple days and would like to find the optimal lambda and beta parameters considering all term structures together.

many thanks!

**Comment by luphord** [comment]
There is no such functionality in this library at the moment.

At first glance I would say it is not too hard to implement using the available primitives. Use `calibrate.betas_ns_ols` to compute optimal betas given lambda for every t. With the betas for every t you can then compute the error function and optimize. Whether this will yield stable and satisfying results is another question.

Are you interested in submitting a pull request?

**Comment by luphord** [comment]
Are you still interested in this topic or can the issue be closed?
