### ISSUE TITLE
Implementation of the Nelson-Siegel-Svensson interest rate curve model

### ISSUE THREAD

**Issue by laza41** [luphord/nelson_siegel_svensson#6]
* Nelson-Siegel-Svensson Model version: 
from nelson_siegel_svensson import NelsonSiegelSvenssonCurve
from nelson_siegel_svensson.calibrate import calibrate_ns_ols
* Python version:
* Operating System:

### Description
Hi,

I have a task: Nelson-Siegel-Svensson model to Fit the yield curve each day using the 6 benchmark yields for the October data.
(Only need 2-year, 3-year, 5-year, 7-year, 10-year, and 30-year maturities)
Importing the data and plot that is no problem. 

I found some codes for Nelson-Siegel-Svensson Model, now I am trying to calibrate. 
### What I Did
So far The code is:
```
Importrates = quandl.get("USTREASURY/YIELD", start_date="2019-10-01", end_date="2019-11-30")
Tyields = Importrates.drop(['1 MO', '2 MO', '3 MO', '6 MO', '1 YR', '20 YR'], axis=1)

t = np.array([2.0, 3.0, 5.0, 7.0, 10.0, 30.0])
y = (Tyields)

curve, status = calibrate_ns_ols(t, y, tau0=1) #NS model calibrate

Also tried this:
t = ([2.0, 3.0, 5.0, 7.0, 10.0, 30.0])
y = (Tyields)

```
As I understand t = maturities and y = yields. Now I`m trying to get the yields from the table, but getting errors :
Mismatching shapes of time and values
or
'list' object has no attribute 'shape' ,

Anyway I know I am doing something wrong.
Can please someone explain or show the code how it can be done from that table for 6 maturities?

thank you in advance!

**Comment by luphord** [comment]
Please take a look at the documentation (https://nelson-siegel-svensson.readthedocs.io/en/latest/nelson_siegel_svensson.html#nelson_siegel_svensson.calibrate.calibrate_ns_ols). There you will find that you need to pass numpy arrays to the calibration function, not Python lists. That is, you need to wrap `t` and `y` with `numpy.array` as in the main example.

Also, you are using `calibrate_ns_ols` which will give you a Nelson-Siegel curve. From your description you might rather want to use `calibrate_nss_ols` for a Nelson-Siegel-Svensson curve.

Finally, `t` and `y` need to be of the same shape. I am not familiar with the quandl API, so I cannot tell if this is the case. But the fact that you have your end date differ from your start date suggests to me that you might get an entire time series, not just a single curve.

**Comment by laza41** [comment]
Hi,

Thank you very much for your response. I managed to fix the issue!
